export const ADD_ACCOUNT = "ADD_ACCOUNT";

export const STORE_TOKEN = "STORE_TOKEN";
export const ADD_DATABASE_ACCOUNT = "ADD_DATABASE_ACCOUNT";
export const LOGOUT = "LOGOUT";
export const SHOW_LOGIN_LOADER = "SHOW_LOGIN_LOADER";